on:
#  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Check all the packages

jobs:
  macos:

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-10.15', 'macos-11.0']
    steps:
      - uses: actions/checkout@v2

      - name: install R
        run: brew install --cask r

      - name: Remove homebrew
        run: |
          curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          sudo /bin/bash uninstall.sh --force
          rm uninstall.sh
          hash -r

      - name: run check script
        run: |
          mkdir fakehome
          cp ~/.gitconfig fakehome/ || touch fakehome/.gitconfig
          cp -Rf ~/.gnupg fakehome/ || mkdir fakehome/.gnupg
          chmod 500 fakehome
          chmod +w fakehome/.gnupg
          unset GITHUB_ACTIONS
          source tests/setupgdal.sh
          HOME="$PWD/fakehome" PATH="$PATH:/Library/Frameworks/R.framework/Resources/bin" Rscript tests/fullcheck.R
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
