on:
  push:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * 0'

name: Test CRAN packages

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-13', 'macos-14', 'macos-15']
    steps:
      - uses: actions/checkout@v3

      - name: Install R from cask (preinstall is homebrew)
        run: brew install --cask r

      - name: Remove homebrew
        run: |
          curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          sudo /bin/bash uninstall.sh --force
          rm uninstall.sh
          hash -r

      - name: run check script
        run: |
          mkdir fakehome
          cp ~/.gitconfig fakehome/ || touch fakehome/.gitconfig
          cp -Rf ~/.gnupg fakehome/ || mkdir fakehome/.gnupg
          chmod 500 fakehome
          chmod +w fakehome/.gnupg
          unset GITHUB_ACTIONS
          HOME="$PWD/fakehome" PATH="$PATH:/Library/Frameworks/R.framework/Resources/bin" Rscript tests/testcran.R
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
